### ISSUE TITLE
Question about installing

### ISSUE THREAD

**Issue by dgleba** [laravella/laravella#25]
I am following the install instructions and it went OK for most of it.

i get:

Database seeded!

  [Exception]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dgnote130c._db_table_action_views' doesn't exist (SQL: upd
  ate `_db_table_action_views` set `title` = ? where `table_id` = ? and `action_id` = ? and `view_id` is null) (Binding
  s: array (
    0 => 'Severities',
    1 => 67,
    2 => 12,
  ))

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dgnote130c._db_table_action_views' doesn't exist

laravella:install

while doing:
C:\p2\xampp\htdocs\laravella>php artisan laravella:install

I tried to run the app anyway and I get:

This webpage has a redirect loop

Can you please help?

**Comment by laravella** [comment]
Hi dgleba,

_db_table_action_views had been renamed to _db_pages in the crud package but the laravella project had not been updated to reflect that.  This is now fixed.

Thanks for the feedback. Please try again and let me know how it goes.

Regards
Victor

**Comment by dgleba** [comment]
Thankyou, that fixed this issue.

I continued to follow the instructions:

cd C:\p2\xampp\htdocs
Git clone https://github.com/laravella/laravella
cd laravella
composer update
In phpmyadmin... I created dgnote_lvl database and granted rights.
php artisan laravella:install
php artisan serve --port 80
Browse to :
http://localhost for the frontend 
http://localhost/admin for admin console 
Default username is superadmin@yourwebsite.com and password is ravel

I got an un-styled login page at localhost/laravella
I logged in.
I got a styled screen. Good.
I clicked on Admin in the top right corner and go an error page something like the image attached. It is a very long error page.

Now I can't get anything but an error page.

Can you help?

![2013-11-01_125129](https://f.cloud.github.com/assets/4622715/1455179/f5637710-4315-11e3-90d1-29895615e0bb.jpg)
