### ISSUE TITLE
[Question] Un-styled pages

### ISSUE THREAD

**Issue by dgleba** [laravella/laravella#27]
After installing, I go to localhost.

The login page is not styled. It is just basic HTML. See attached screen shots.

The contents page looks OK. Many of the pages look OK.

Some pages don't look like they are displaying correctly. Eg: When I press 'home' or 'account' I get unstyled pages. See attached screen shots.

Can someone comment?

Thanks in advance.

![unstyled login page screenshot 2013-11-02 11 54 33](https://f.cloud.github.com/assets/4622715/1465330/f01a81c6-455f-11e3-9a53-9d91c23b0600.png)

![contents page ok screenshot 2013-11-02 11 57 07](https://f.cloud.github.com/assets/4622715/1465332/fc5bd570-455f-11e3-8082-aaccab9b716e.png)

![after press account button 2013-11-04_084642](https://f.cloud.github.com/assets/4622715/1465340/0b590408-4560-11e3-8436-c336bcf59abe.jpg)

![unstyled when press home screenshot 2013-11-02 11 57 50](https://f.cloud.github.com/assets/4622715/1465343/19bb9d6c-4560-11e3-9fab-a3e18e1a0fe3.png)

**Comment by laravella** [comment]
I've seen this and fixed it, I'm busy uploading the fix...
Will be ready in a moment...

**Comment by laravella** [comment]
Ok, try now...

**Comment by dgleba** [comment]
OK thanks.
I am not sure I should have done the following. Please advise.

I did:  git pull  ..  to update from github.
Then I did:
php artisan laravella:install

I got an error.

Can someone help?

~=-=-=-=-=-=~ 

  [InvalidArgumentException]
  Command "skins:update" is not defined.

  Did you mean one of these?
      Skins:update
      cms:update

laravella:install

~=-=-=-=-=-=~ 

Screen shot is also attached.

![error after install again 2013-11-04_112605](https://f.cloud.github.com/assets/4622715/1466250/7bb7544e-456e-11e3-8e7e-21faf795e6ce.jpg)

**Comment by laravella** [comment]
You would need to do a 
composer update (or php composer.phar update, depending on your installation)
after you did the git pull.

The git pull is necessary to update the project
the composer update updates the packages.

**Comment by dgleba** [comment]
Before you answered, I started over with an empty folder to see what would happen:

-renamed the laravella folder to laravella1
-cd C:\p2\xampp\htdocs
Git clone https://github.com/laravella/laravella
cd laravella
composer update
:I used the already existing database..... I didn't: [In phpmyadmin... I created dgnote_lvl database and granted rights.]
php artisan laravella:install
php artisan serve --port 88

I get a styled login page, but when I press the [account] button in the top right corner to the left of the [logout] button, I get an un-styled page.

see screenshots below.

Can you comment?

Thanks in advance for your efforts.

The Account button is shown on the picture below in the top right corner next to the logout button..
![ok 2013-11-04_153014](https://f.cloud.github.com/assets/4622715/1468286/372d3358-4590-11e3-9cd7-91f326240e61.jpg)

Unstyled page:
![unstyled 2013-11-04_145207](https://f.cloud.github.com/assets/4622715/1468289/3f9d235e-4590-11e3-863e-f127974a30c8.jpg)

**Comment by laravella** [comment]
Ok, I've fixed the /accounts page's skin

You'll need the the new AccountController.php from the root project (laravella/laravella) so you would need to do a 

git pull 

in addition to 

composer update laravella/skins

--Victor

apologies for previous incorrect post

**Comment by dgleba** [comment]
Thanks for your help.
It's working like a charm.
:)
