### ISSUE TITLE
Error to get firecracker on bitbucket

### ISSUE THREAD

**Issue by Soufraz** [laravella/laravella#28]
Hi,
When I run the composer update and put my login and password, I get the follow message:

```
[RuntimeException]                                                           
  Failed to clone git@bitbucket.org:dataphile/firecracker.git, could not read  
   packages from it                                                            

  Permission denied (publickey).                                               
  fatal: Could not read from remote repository.                                

  Please make sure you have the correct access rights                          
  and the repository exists. 
```

What is wrong?

**Comment by laravella** [comment]
Hi Rafael

Please use the latest stable release : 

https://github.com/laravella/laravella/releases/tag/v4.0.20131108

Regards
Victor

**Comment by Soufraz** [comment]
I run the composer update and install, after this, I get this error:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel._db_options' doesn't exist (SQL: select `o`.`value` from `_db_options` as `o` where `o`.`name` = ? limit 1) (Bindings: array ( 0 => 'skin', ))
```

There is a dump of default table? I run the install.cmd and not yet.

**Comment by laravella** [comment]
Rafael, 

Did you download the latest stable release?
and did you configure you /app/config/database.php correctly before you did the install? 
did the install complete successfully?

**Comment by Soufraz** [comment]
So..
Later I'll try a new installation. Thanks!!

**Comment by laravella** [comment]
Please see the v4.0.20140220 release : 

https://github.com/laravella/laravella/releases/tag/v4.0.20140220
